- encode_value.go
- main_test.go
Should fix https://github.com/go-pg/pg/issues/48#issuecomment-89508928
> Handle encoding pointer to the time.Time.

- types.go
Fixes https://github.com/go-pg/pg/issues/100
> Fix reflect for Go 1.6.

- conv_test.go
- messages.go
- orm/delete.go
- orm/field.go
- orm/format.go
- orm/insert.go
- orm/model_struct.go
- orm/select.go
- orm/update.go
- orm/util.go
- pg.go
- types/append.go
- types/append_jsonb.go
- types/append_jsonb_test.go
- types/append_test.go
- types/append_value.go
- types/array.go
- types/decode_value.go
- types/interface.go
- types/time.go
Updates https://github.com/go-pg/pg/issues/118
> Improve array support.

- example_test.go
- stmt.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/140
> Add RunInTransaction example.

- conv_test.go
- types/append.go
Fixes https://github.com/go-pg/pg/issues/165
> Fix escaping array of strings.

- README.md
- db_test.go
- orm/field.go
- orm/insert.go
- orm/kinds.go
- orm/model.go
- orm/table.go
- orm/util.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/186
> Omit nullable fields from inserts.

- db_test.go
- orm/delete.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/192
> Return an error when model does not have pks.

- internal/util.go
- orm/model_slice.go
- orm/model_table_slice.go
- orm/util.go
- types/scan_array.go
```
benchmark                            old ns/op     new ns/op     delta
BenchmarkModelHasOneGopg-4           314800        282860        -10.15%
BenchmarkModelHasManyGopg-4          3166363       3199460       +1.05%
BenchmarkModelHasMany2ManyGopg-4     3557399       3453010       -2.93%
benchmark                            old allocs     new allocs     delta
BenchmarkModelHasOneGopg-4           1173           1081           -7.84%
BenchmarkModelHasManyGopg-4          6596           6504           -1.39%
BenchmarkModelHasMany2ManyGopg-4     8619           8527           -1.07%
benchmark                            old bytes     new bytes     delta
BenchmarkModelHasOneGopg-4           77573         62844         -18.99%
BenchmarkModelHasManyGopg-4          390383        375674 …
```
> Move SliceNextElem to internal package and reuse it.

- conv_test.go
- db_test.go
- orm/field.go
- orm/table.go
- types/append_value.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/204
> Fix null values handling.

- orm/delete.go
- orm/insert.go
- orm/query.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/210
> orm: append table alias only when ON CONFLICT is used.

- orm/format_test.go
- types/append_value.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/215
> types: fix scanning and appending interfaces.

- db.go
- db_test.go
- example_model_test.go
- orm/insert.go
- orm/model_table.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/query.go
- race_test.go
Fixes https://github.com/go-pg/pg/issues/218
> orm: support bulk inserts.

- README.md
- pg.go
Updates https://github.com/go-pg/pg/issues/232
> Document query logger.

- conv_test.go
- internal/parser/array_parser.go
- internal/parser/array_parser_test.go
- internal/parser/parser.go
- orm/format.go
- types/append_array.go
- types/append_value.go
- types/parser.go
- types/scan_array.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/226
> Support nested arrays.

- conv_test.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/231
> Scan 1 as boolean true.

- options.go
I use 20 in my projects so it should be safe default :)
> Increase default PoolSize.

- orm/field.go
- orm/table.go
- orm/table_test.go
Fixes https://github.com/go-pg/pg/issues/257
> Fix primary key detection.

- README.md
- example_model_test.go
- orm/join.go
- orm/model_table_struct.go
- orm/query.go
- orm/relation.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/263
> Add support for belongs to relation.

- example_model_test.go
- orm/join.go
- orm/model.go
- orm/model_m2m.go
- orm/model_many.go
- orm/model_table.go
- orm/model_table_slice.go
- orm/relation.go
- orm/table.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/263
> Fix slice model to work with slice of ptrs.

- README.md
- example_model_test.go
- orm/join.go
- orm/model_table.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/266
> Add ability to change relation Query.

- internal/pool/conn.go
- messages.go
- stmt.go
```
benchmark                           old allocs     new allocs     delta
BenchmarkQueryRowsGopgDiscard-4     14             2              -85.71%
benchmark                           old bytes     new bytes     delta
BenchmarkQueryRowsGopgDiscard-4     96            26            -72.92%
```
> Better columns cache.

- db_test.go
- orm/join.go
- orm/model_table_struct.go
- orm/orm.go
- orm/query.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/280
> Fix hasOne to hasOne relation.

- db.go
- messages.go
- options.go
Fixes https://github.com/go-pg/pg/issues/283
> Allow setting tls.Config.

- db_test.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/280#issuecomment-239915283
> Fix slice of ptrs.

- db_test.go
- orm/join.go
Fixes https://github.com/go-pg/pg/issues/297
> Add M2M filtering.

- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/299
> types: scan nil interface as JSONB.

- .travis.yml
- orm/kinds.go
Fixes https://github.com/go-pg/pg/issues/301
> orm: check for nil ptrs in isZero.

- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/304
> Select only known columns.

- orm/table.go
- orm/table_test.go
Fixes https://github.com/go-pg/pg/issues/306
> orm: include struct field.

- orm/query.go
Fixes https://github.com/go-pg/pg/issues/319
> orm: support values in Update.

- orm/orm.go
Fixes https://github.com/go-pg/pg/issues/327
> Complete orm.DB interface.

- README.md
- example_model_test.go
- exampledb_placeholders_test.go
- internal/parser/parser.go
- orm/format.go
- orm/format_test.go
Fixes https://github.com/go-pg/pg/issues/333#issuecomment-248007285
> Add support for indexed placeholders.

- db.go
- db_test.go
- orm/create_table.go
- orm/create_table_test.go
- orm/field.go
- orm/table.go
- orm/tables.go
- tx.go
Updates https://github.com/go-pg/pg/issues/313
> Add CreateTable function.

- README.md
- db_test.go
- orm/join.go
- orm/model_table.go
- orm/model_table_struct.go
- orm/query.go
- orm/select.go
- orm/table.go
Updates https://github.com/go-pg/pg/issues/346#issuecomment-250225468
> orm: add override tag support.

- options.go
Fixes https://github.com/go-pg/pg/issues/342
> Support Dialer.

- db_test.go
- orm/model_table_m2m.go
- orm/model_table_many.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/398
> Fix slice of ptrs handling and improve zeroing.

- README.md
Updates https://github.com/go-pg/pg/issues/393
> Table name docs.

- db_test.go
- orm/model_scan.go
- orm/model_table_struct.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/412
> orm: improve error messages.

- db_test.go
- orm/count_estimate.go
- orm/join_test.go
- orm/query.go
- orm/select.go
- orm/select_test.go
- orm/url_values_test.go
Fixes https://github.com/go-pg/pg/issues/415
> orm: fix count queries.

- README.md
- db.go
- example_test.go
- orm/create_table.go
- orm/create_table_test.go
- orm/field.go
- orm/table.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/363
> orm: recognize unique tag.

- orm/join.go
- orm/join_test.go
- orm/select_test.go
- types/append_field.go
Fixes https://github.com/go-pg/pg/issues/422
> orm: quote aliases when generating joins.

- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/423#issuecomment-264089487
> orm: generate joins for count queries.

- README.md
- example_model_test.go
- orm/query.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/422#issuecomment-263541732
> Allow omitting model column names and add examples.

- orm/insert_test.go
Updates https://github.com/go-pg/pg/issues/432
> orm: add embedding test.

- orm/url_values.go
- orm/url_values_test.go
- other fixes for order empty string
> Add `ieq` : `ILIKE` and `match` : `SIMILAR TO` in `url_values`

- db_test.go
- hook_test.go
- listener_test.go
- loader_test.go
- main_test.go
- orm/insert_test.go
- orm/model_table.go
- orm/model_table_m2m.go
- orm/model_table_many.go
- orm/model_table_struct.go
- orm/util.go
- pool_test.go
- race_test.go
- tx_test.go
Fixes https://github.com/go-pg/pg/issues/444
> Fix override and m2m relation.

- db.go
- db_test.go
- example_test.go
- internal/pool/buffer.go
- main_test.go
- messages.go
Fixes https://github.com/go-pg/pg/issues/451
> Fix TLS connections.

- options.go
- options_test.go
Added a method to parse database URL to use in environments like Heroku (described in #445) including some sanity checks.
> Add ParseURL method

- orm/create_table_test.go
- orm/field.go
- orm/kinds.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/462
> Recognize sql.Null* in CreateTable.

- orm/join.go
- orm/query.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/464
> orm: fix query generation for joins and _.

- example_model_test.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/479#issuecomment-283733374
> orm: add WhereIn.

- tx.go
Fixes https://github.com/go-pg/pg/issues/468
> Rollback transaction on panic

- db.go
- internal/internal.go
- orm/format_test.go
- orm/query.go
- stmt.go
Fixes https://github.com/go-pg/pg/issues/497
> Retry connections as well

- orm/create_table_test.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/505
> orm: recognize byte slice and array in CreateTable

- orm/create_table.go
> orm: Add IgnoreExists option for CreateTable

- orm/select_test.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/496
> orm: auto-quote custom table name if it is a keyword

- CHANGELOG.md
- db.go
- db_context.go
- db_no_context.go
- hook.go
- orm/format.go
Fixes https://github.com/go-pg/pg/issues/528
> Add context support

- orm/create_table.go
- orm/create_table_test.go
- orm/field.go
- orm/hook.go
- orm/model.go
- orm/model_table_m2m.go
- orm/model_table_many.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/table.go
- orm/table_test.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/474
> Recognize SQL arrays types

- listener.go
- listener_test.go
- types/append_field.go
- types/interface.go
Fix https://github.com/go-pg/pg/issues/532
> Fix channel name quotting

- orm/create_table.go
- orm/join.go
- orm/query.go
- orm/relation.go
- orm/select.go
- orm/table.go
- orm/util.go
Fixes https://github.com/go-pg/sharding/issues/36#issuecomment-299629015
> Format table name in joins

- db.go
- orm/drop_table.go
- orm/drop_table_test.go
- orm/query.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/542
> Add DropTable

- orm/table.go
Fixes https://github.com/go-pg/pg/issues/547
> orm: don't share slice between fields

- CHANGELOG.md
- db.go
- db_test.go
- example_model_test.go
- orm/delete.go
- orm/field.go
- orm/insert.go
- orm/insert_test.go
- orm/join.go
- orm/orm.go
- orm/query.go
- orm/select.go
- orm/table.go
- orm/table_test.go
- orm/update.go
- orm/update_test.go
- orm/util.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/554
> Support bulk updates

- db_test.go
- loader_test.go
- messages.go
- orm/hook.go
- orm/insert.go
- orm/model.go
- orm/model_discard.go
- orm/model_scan.go
- orm/model_slice.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/query.go
- pg.go
Fixes https://github.com/go-pg/pg/issues/366#issuecomment-310077931
> Allow scanning returning data in DELETE queries

- orm/format.go
- orm/query.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/569
> Accept queries in formatter

- orm/table.go
Updates https://github.com/go-pg/pg/issues/581
> orm: allow customizing has one prefix

- orm/model_table_m2m.go
Fixes https://github.com/go-pg/pg/issues/583
> orm: use relation base prefix

- db_test.go
- orm/format.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/586
> orm: add Query and Exec to Model

- orm/table.go
Fixes https://github.com/go-pg/pg/issues/588#issuecomment-317240260
> orm: improve fk handling

- tx.go
connection should be closed if "tx.Exec("BEGIN")" fail
> fix connection leak in case tx begin error

- db_test.go
- hook_test.go
- orm/create_table.go
- orm/drop_table.go
- orm/insert.go
- orm/model.go
- orm/model_table.go
- orm/model_table_struct.go
- orm/query.go
- orm/query_test.go
- orm/select_test.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/578
> Allow pg.Model((*Book)(nil))

- orm/table.go
- orm/table_test.go
- orm/tables.go
Fixes https://github.com/go-pg/pg/issues/597
> orm: fix table for models with circular reference

- orm/insert.go
- orm/insert_test.go
- orm/query.go
- orm/query_test.go
Fixes https://github.com/go-pg/pg/issues/601
> Fix where clause for SelectOrInsert with do update

- db_test.go
- orm/join.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/604
> orm: deduplicate ids when generating join queries

- README.md
- internal/parser/parser.go
- orm/create_table_test.go
- orm/table.go
- orm/tag.go
- orm/tag_test.go
Fixes https://github.com/go-pg/pg/issues/603
> Better tag parser

- orm/query.go
Fixes https://github.com/go-pg/pg/pull/616
> orm: check if model has pks in First and Last

- db.go
- internal/parser/parser.go
- orm/create_table.go
- orm/create_table_test.go
- orm/field.go
- orm/table.go
- orm/tag.go
- orm/tag_test.go
Fixes https://github.com/go-pg/pg/issues/611
> Allow setting sql default value

- orm/field.go
- orm/query.go
- orm/table.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/622
> orm: specify type in bulk update

- orm/inflection.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/623
> orm: allow setting table name inflector

- db.go
- db_context.go
- db_no_context.go
- db_test.go
- export_test.go
- internal/pool/pool_single.go
- options.go
Fixes https://github.com/go-pg/pg/issues/631
> Add OnConnect hook

- orm/query.go
- orm/query_test.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/630
> orm: support FOR UPDATE

- example_model_test.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/524. This is rather specific and hacky, but does the job with minimum changes.
> orm: add json_use_number tag

- db.go
- db_test.go
- messages.go
Fixes https://github.com/go-pg/pg/issues/613
> Wait for readyForQuery when error happens in copyFrom and copyIn

- internal/pool/write_buffer.go
Fixes https://github.com/go-pg/pg/issues/594
> internal/pool: fix vet warning

- db_test.go
- orm/create_table.go
- orm/drop_table.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/628
> Add CreateTableOptions.FKConstraints

- orm/create_table_test.go
- orm/field.go
- orm/table.go
- orm/tag.go
- orm/tag_test.go
Fixes https://github.com/go-pg/pg/issues/645
> More flexible tag parsing

- db_test.go
- internal/pool/pool.go
- listener_test.go
This is more reliable if you want number of misses
> Replace PoolStats.Requests with PoolStats.Misses

- orm/insert.go
- orm/insert_test.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/642
> orm: allow specifying Column in insert queries

- example_model_test.go
- orm/field.go
- orm/query.go
- orm/update.go
- orm/update_test.go
Fixes https://github.com/go-pg/pg/issues/655
> Add Query.UpdateNotNull

- db_test.go
- orm/model_table_slice.go
- orm/model_table_struct.go
Fixes https://github.com/go-pg/pg/issues/671
> orm: don't initialize nil struct when value is null

- orm/query.go
Fixes https://github.com/go-pg/pg/issues/670
> orm: better doc for Query.First and Query.Last

- types/append_value.go
Fixes https://github.com/go-pg/pg/issues/679
> types: define array bytes appender

- tx.go
> add context.Context support for transactions

- db_test.go
- example_model_test.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/688
> Set custom type flag on timestamptz

- example_model_test.go
- orm/query.go
- pg.go
- types/in_op.go
Replaces https://github.com/go-pg/pg/pull/687
> Support multiple values in pg.In

- tx.go
Fixes https://github.com/go-pg/pg/issues/684. This is important so users can swap `DB` and `Tx` and use them concurrently.
> Make Tx safe for concurrent use by multiple goroutines

- db.go
- db_context.go
- db_no_context.go
- orm/orm.go
Fixes https://github.com/go-pg/pg/issues/705
> Copy context in WithParam and WithTimeout

- orm/table.go
Fixes https://github.com/go-pg/pg/issues/706
> Improve foreign key detection

- orm/query.go
- orm/select.go
Fixes https://github.com/go-pg/pg/issues/703
> Add Query.WherePK

- orm/table.go
- orm/table_test.go
Fixes https://github.com/go-pg/pg/issues/715
> orm: fix autodetection on anonymous model

- messages.go
- orm/hook.go
- orm/model.go
- orm/model_discard.go
- orm/model_scan.go
- orm/model_slice.go
- orm/query.go
- pg.go
Fixes https://github.com/go-pg/pg/issues/712
> Add HooklessModel to reduce boilerplate

- db_test.go
- orm/join.go
- orm/model_table_m2m.go
- orm/model_table_many.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/729
> orm: fix panic when relation does not have results

- internal/unsafe.go
Copy of https://github.com/go-redis/redis/pull/693
> Fix unsafe

- db_test.go
- orm/insert.go
Fixes https://github.com/go-pg/pg/issues/747
> orm: return an error when trying to bulk insert empty slice

- example_test.go
- orm/hook.go
- orm/model_table_struct.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/754
> orm: add discard_unknown_columns option

- CHANGELOG.md
- example_test.go
- orm/create_table.go
- orm/create_table_test.go
- orm/field.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/669
> orm: make ON DELETE options and allow changing its value

- CHANGELOG.md
- db_test.go
- example_model_test.go
- internal/underscore.go
- orm/field.go
- orm/join.go
- orm/query.go
- orm/table.go
- orm/tag.go
- orm/tag_test.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/766
> orm: rework fk and joinFK

- orm/join.go
- orm/model_table_m2m.go
- orm/relation.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/768
> orm: add fk value

- listener.go
- orm/format.go
- orm/insert.go
- orm/insert_test.go
- orm/query.go
- orm/query_test.go
- orm/select.go
- orm/update.go
- orm/update_test.go
- orm/zero.go
- pg.go
- time.go
- types/append.go
- types/array.go
- types/hstore.go
- types/in_op.go
- types/in_op_test.go
- types/interface.go
Fixes https://github.com/go-pg/pg/issues/770
> orm: add Query.Value

- types/append.go
> Special format for NaN and Infinity float numbers

- db_test.go
- orm/create_table.go
- orm/create_table_test.go
- orm/query.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/719#issuecomment-366974041
> Support creating multi-column unique indexes

- orm/create_table_test.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/791
> orm: automatically provide hstore type

- db.go
- db_test.go
- orm/insert.go
- orm/insert_test.go
- orm/model_table_slice.go
- orm/update.go
- orm/update_test.go
- stmt.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/789
> Add sliceTableModel.AppendParam for bulk updates

- orm/field.go
- orm/join.go
- orm/model_table_m2m.go
- orm/relation.go
- orm/table.go
- orm/tables.go
- orm/util.go
Updates https://github.com/go-pg/pg/issues/792
> orm: add support for pk_ and fk_ convention

- example_many2many_self_test.go
- example_many2many_test.go
Fixes https://github.com/go-pg/pg/issues/825
> Better many to many example

- README.md
- bench_test.go
- db_test.go
- example_model_test.go
- orm/count_estimate.go
- orm/model_func.go
- orm/model_scan.go
- orm/query.go
Updates https://github.com/go-pg/pg/issues/448
```
BenchmarkForEachReal-4   	      20	  87856609 ns/op	 6403013 B/op	  200020 allocs/op
BenchmarkForEachFake-4   	      10	 173835957 ns/op	559478715 B/op	  100049 allocs/op
```
> orm: add ForEach

- orm/query.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/843#issuecomment-388356380
> orm: support empty where group

- orm/table_test.go
Updates https://github.com/go-pg/pg/issues/856
> orm: add table init race test

- orm/tables.go
Fixes https://github.com/go-pg/pg/issues/864
> orm: fix getByName

- orm/join.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/870
> orm: allow overwrite has many columns

- db_test.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/872
> orm: fix ptr bulk delete

- orm/insert.go
- orm/insert_test.go
- orm/model_table_struct.go
- orm/query.go
- orm/update.go
- orm/update_test.go
- orm/util.go
Fixes https://github.com/go-pg/pg/issues/879
> orm: fix Value for bulk updates

- orm/internal_test.go
- orm/table.go
- orm/table_test.go
Updates https://github.com/go-pg/pg/issues/891
> orm: improve tables race test

- orm/internal_test.go
- orm/table.go
Updates https://github.com/go-pg/pg/issues/891
> orm: fix tables init race

- orm/format.go
- orm/select_test.go
> Fix formatting structs in Where with params

- orm/query.go
> Add info about param expansion

- conv_test.go
- types/append.go
- types/append_array.go
- types/append_value.go
Fixes https://github.com/go-pg/pg/issues/922
> types: properly append NaN, +Inf and -Inf in arrays

- orm/model_table.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/931
> orm: apply fn to the query for has one and belongs to

- db.go
- listener.go
Fixes https://github.com/go-pg/pg/issues/925
> Fix Channel to use Receive without timeout

- db_test.go
- internal/pool/conn.go
- internal/pool/elastic_reader.go
- internal/pool/pool.go
- messages.go
Fixes https://github.com/go-pg/pg/issues/937
> Fix error handling in Prepare

- orm/field.go
- orm/insert.go
- orm/insert_test.go
- orm/update.go
- orm/update_test.go
Fixes https://github.com/go-pg/pg/issues/940
> orm: tweak notnull and default behavior

- options.go
- options_test.go
> Add sslmode=require support in ParseURL

- orm/model_table_slice.go
- orm/model_table_struct.go
Fixes https://github.com/go-pg/pg/issues/945
> orm: return an error when struct can't be initialized

- orm/join.go
- orm/query.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/943
> orm: support JoinOn in Relation

- hook_test.go
- loader_test.go
- orm/hook.go
- orm/model.go
- orm/model_table_struct.go
- orm/query.go
- orm/table.go
Updates https://github.com/go-pg/pg/issues/952
> Add BeforeSelectQuery hook

- orm/delete.go
- orm/insert.go
- orm/join.go
- orm/query.go
- orm/select.go
- orm/select_test.go
- orm/table.go
- orm/update.go
Updates https://github.com/go-pg/pg/issues/952
> orm: add ability to set table name for select queries

- example_soft_delete_test.go
- example_test.go
- orm/query.go
Updates https://github.com/go-pg/pg/issues/952#issuecomment-418413363
> orm: update only deleted_at column

- orm/table.go
- orm/table_test.go
Fixes https://github.com/go-pg/pg/issues/988
> orm: set some alias for anonymous structs

- example_test.go
Fixes https://github.com/go-pg/pg/issues/990
> Add ExampleError_IntegrityViolation

- example_model_test.go
- orm/insert_test.go
- orm/query.go
- orm/select.go
- orm/table.go
- orm/table_create.go
- orm/table_drop.go
Fixes https://github.com/go-pg/pg/issues/992
> orm: support models with dynamic table name

- orm/table.go
- orm/table_create_test.go
- types/append_value.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/996
> Add support for json.RawMessage

- conv_test.go
- types/append.go
Fixes https://github.com/go-pg/pg/issues/1008
> Fix appending array of bytes

- orm/join.go
- orm/model_table_struct.go
- orm/query.go
- orm/select.go
- orm/table.go
- orm/table_create.go
- orm/table_test.go
- orm/tables.go
Updates https://github.com/go-pg/pg/issues/728
> Add table name and full name

- orm/table.go
Fixes https://github.com/go-pg/pg/issues/1032
> orm: recursive inline struct tables

- orm/insert.go
- orm/insert_test.go
Fixes https://github.com/go-pg/pg/issues/1038
> orm: support default SET in INSERT ... ON CONFLICT DO UPDATE

- db.go
- hook.go
- hook_test.go
- stmt.go
- tx.go
> Add OnQueryStarted hook

- types/append_jsonb.go
Fixes https://github.com/go-pg/pg/issues/1064
> types: fix jsonb array appender

- internal/tag/tag.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/1046
> Support nopk tag

- base.go
Fixes https://github.com/go-pg/pg/issues/1080
> Fix OnConnect

- base.go
- stmt.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/1045
Fixes https://github.com/go-pg/pg/issues/137
> Use defer to free conn

- base.go
Fixes https://github.com/go-pg/pg/issues/1092
> Fix withConn

- example_test.go
- orm/field.go
- orm/table.go
- orm/table_create.go
- orm/table_create_test.go
Add ON UPDATE clause to CREATE TABLE query, similar to ON DELETE one.
> add ON UPDATE clause to CREATE TABLE

- db.go
Fixes https://github.com/go-pg/pg/issues/1090
> Fix race in WithContext

- base.go
- db_test.go
- hook_test.go
- orm/hook.go
- orm/model.go
- orm/model_table_m2m.go
- orm/model_table_many.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/query.go
- orm/table.go
- stmt.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/1109
> Add context.Context into hooks

- orm/model_table_struct.go
Fixes https://github.com/go-pg/pg/issues/1122
> orm: fix nil time ptr

- orm/composite.go
Fixes https://github.com/go-pg/pg/issues/1129
> orm: fix scanning null values in composites

- internal/pool/pool_single.go
Fixes https://github.com/go-pg/pg/issues/1134
> Implement SinglePool.NewConn

- internal/struct_filter/field.go
- orm/struct_filter_test.go
FIxed an error in a struct_filter field and added some tests.
> struct_filter: ILIKE fix

- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1148
> orm: preserve context in Query.New

- orm/count_estimate.go
Fixes https://github.com/go-pg/pg/issues/1151
> orm: handle an error creating a func concurrently

- orm/composite.go
Fixes https://github.com/go-pg/pg/issues/1160
> orm: use ROW() to append composites

- listener.go
Fixes https://github.com/go-pg/pg/issues/1155
> Fix DB.Listen to re-subscribe to channels on error

- orm/join.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1162
> orm: fix soft delete and WHERE with OR

- base.go
- internal/pool/pool_single.go
- stmt.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/1169
Closes https://github.com/go-pg/pg/pull/1170
> Change SingleConnPool to remove bad connection

- example_model_test.go
- orm/query.go
- pg.go
- types/in_op.go
- types/in_op_test.go
Closes https://github.com/go-pg/pg/issues/1158
> Sync pg.In and Query.WhereIn

- db_test.go
- main_test.go
- orm/field.go
Fixes https://github.com/go-pg/pg/issues/1146#issuecomment-477393259
> Fix scanning into nil embedded struct pointer

- types/scan.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/1188
> Add scanArrayBytesValue

- orm/table.go
- testdata/issue1214.go
Fixes https://github.com/go-pg/pg/issues/1214
> orm: don't detect relations on fields with custom type

- orm/delete.go
- orm/query.go
- orm/select.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/1219#issuecomment-495095555
> Use Where provided by user when possible

- orm/query.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/998
> orm: support distinct and distinct on

- base.go
- hook.go
- hook_test.go
- stmt.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/1226
> Pass and return context in hooks

- db_test.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1232
> orm: fix soft delete on nil model

- db_test.go
- orm/table.go
Fixes https://github.com/go-pg/pg/issues/1237
> orm: check field kind

- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1242
> orm: add WithInsert and WithUpdate

- orm/insert.go
- orm/insert_test.go
- orm/query.go
- orm/update.go
Fixes https://github.com/go-pg/pg/issues/1220
> orm: allow specifying extra value

- example_placeholders_test.go
- internal/structfilter/struct.go
- internal/util.go
- orm/delete_test.go
- orm/insert_test.go
- orm/join.go
- orm/join_test.go
- orm/query_test.go
- orm/select_test.go
- orm/table.go
- orm/table_create_test.go
- orm/table_drop_test.go
- orm/table_test.go
- orm/update_test.go
- urlvalues/url_filter_test.go
Fixes https://github.com/go-pg/pg/issues/1252
Fixes https://github.com/go-pg/pg/issues/1247#issuecomment-504705323
> Restore table and column quotes

- base.go
- db_test.go
- hook.go
- hook_test.go
- orm/hook.go
- orm/model.go
- orm/model_table_m2m.go
- orm/model_table_many.go
- orm/model_table_slice.go
- orm/model_table_struct.go
- orm/query.go
- orm/table.go
- stmt.go
- tx.go
Updates https://github.com/go-pg/pg/pull/1256
> orm: rework model hooks

- internal/pool/pool_single.go
- internal/pool/pool_single_test.go
Closes https://github.com/go-pg/pg/pull/1270
> Fix deadlock in single conn pool

- example_custom_test.go
Fixes https://github.com/go-pg/pg/issues/1267
> Add custom type example

- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1288
> Add AllWithDeleted

- CHANGELOG.md
- README.md
- example_model_test.go
- orm/field.go
- orm/format_test.go
- orm/insert.go
- orm/insert_test.go
- orm/query.go
- orm/table.go
- orm/update.go
- orm/update_test.go
Fixes https://github.com/go-pg/pg/issues/1306
Fixes https://github.com/go-pg/pg/issues/1304
> Change sql notnull and add pg usezero tags

- CHANGELOG.md
- README.md
- base.go
- db_test.go
- example_soft_delete_test.go
- orm/field.go
- orm/format_test.go
- orm/insert_test.go
- orm/table.go
- orm/table_create.go
- orm/table_create_test.go
- orm/update_test.go
Updates https://github.com/go-pg/pg/issues/1306
> Add nullable and zeroable tags

- CHANGELOG.md
- README.md
- orm/field.go
- orm/format_test.go
- orm/insert_test.go
- orm/table.go
- orm/table_create.go
- orm/table_create_test.go
- orm/update_test.go
Closes https://github.com/go-pg/pg/issues/1310
> Make all columns nullable by default just like it used to be

- db_test.go
- messages.go
Fixes https://github.com/go-pg/pg/issues/1311
> Fix CopyTo to handle ErrBufferFull

- base.go
- hook.go
- hook_test.go
- messages.go
- orm/count_estimate.go
- orm/format.go
- orm/orm.go
- orm/query.go
- tx.go
Fixes https://github.com/go-pg/pg/issues/1321
> Fix formatting table params in FormattedQuery

- orm/query.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/1342
> orm: fix AllWithDeleted

- orm/format.go
- orm/insert_test.go
- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1349
> orm: fix insert and ExcludeColumn

- tx.go
Fixes https://github.com/go-pg/pg/issues/1372
> Use tx.ctx instead of creating new context

- orm/query.go
- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/1370
> orm: add support for unions

- orm/composite_create.go
- orm/field.go
- orm/table.go
- orm/table_create.go
- orm/table_create_test.go
Fixes https://github.com/go-pg/pg/issues/1388
> orm: always use SQL type provided by the user

- types/append.go
- types/append_value.go
- types/scan_value.go
Closes https://github.com/go-pg/pg/issues/1390
> types: add RegisterAppender and RegisterScanner

- go.mod
- go.sum
- types/append_value.go
- types/scan_value.go
Fixes https://github.com/go-pg/pg/issues/1417
> types: don't error if there is a race

- orm/select_test.go
- orm/struct_filter.go
- orm/struct_filter_test.go
Fixes https://github.com/go-pg/pg/issues/1407
> orm: fix empty struct filter

- options.go
- options_test.go
Closes https://github.com/go-pg/pg/issues/1438
> Add ?sslmode=verify-ca and ?sslmode=verify-full

- orm/select.go
- orm/select_test.go
Fixes https://github.com/go-pg/pg/issues/1488
> orm: fix union to support order

- orm/query.go
Fixes https://github.com/go-pg/pg/issues/1208#issuecomment-570507676
> orm: don't use QueryOne with returning null

- db_test.go
- orm/model_table_struct.go
- orm/query.go
- orm/table.go
> soft delete with bigint column

- orm/model_table_struct.go
- orm/table.go
For https://github.com/go-pg/pg/pull/1497
> orm: cleanup int64 support for soft delete

- conv_test.go
- db_test.go
- orm/table.go
- pgjson/json.go
- pgjson/provider.go
- types/append_jsonb_test.go
- types/append_value.go
- types/scan_value.go
Closes https://github.com/go-pg/pg/pull/1548
> add possibility to override json library for jsonb fields

- base.go
Fixes https://github.com/go-pg/pg/issues/1569
> Reset SingleConnPool if conn can't be initialized

- base.go
- hook_test.go
Note for reviewer: Model field of QueryEvent filled if latest query argument is orm.TableModel. I found such approach in project. Is it good or it's better to not fill QueryEvent.Model?
Will close #1564
> Call QueryHook-s for CopyFrom/CopyTo queries

- CHANGELOG.md
- README.md
- conv_test.go
- db_test.go
- example_test.go
- listener_test.go
- orm/format_test.go
- orm/insert_test.go
- orm/query.go
- orm/types.go
- pg.go
- pool_test.go
- tx.go
Nothing serious, just a few linting tweaks. Feel free to cherry pick what you like.
> Minor linting tweaks

- base.go
- go.mod
- orm/delete.go
- orm/insert.go
- orm/query.go
- orm/select.go
- orm/update.go
- pgext/pgext.go
Updates https://github.com/go-pg/pg/issues/1470
> Add OpenTelemetryHook

- conv_test.go
- types/append.go
- types/append_value.go
- types/flags.go
- types/scan_value.go
Closes https://github.com/go-pg/pg/pull/1624
> Fix nil driver.Valuer

- internal/pool/pool_single.go
- tx.go
- tx_test.go
Fixes https://github.com/go-pg/pg/issues/1611
> Fix Stmt pool inside a Tx
