go-pg/pg

README.md
bench_test.go
db.go
example_complexQuery_test.go
example_json_test.go
exampledb_query_test.go

Before:
```
BenchmarkQueryRows	     500	   3277206 ns/op	  923744 B/op	    8034 allocs/op
```
After:
```
BenchmarkQueryRows	     500	   2588617 ns/op	  843561 B/op	    7031 allocs/op
```

Use faster collections in examples.

---

.travis.yml
README.md
bench_test.go
db.go
db_test.go
example_complexQuery_test.go
example_json_test.go
exampledb_query_test.go
listener_test.go
loader.go
loader_test.go
main_test.go
messages.go
pool_test.go
stmt.go
tx.go
tx_test.go
types_test.go

New reflect based collections are only slightly slower
```
BenchmarkQueryRows-4                    	   10000	    181824 ns/op	   90989 B/op	     724 allocs/op
BenchmarkQueryRowsReflect-4             	   10000	    199050 ns/op	  102224 B/op	     925 allocs/op
BenchmarkQueryRowsStdlibPq-4            	    5000	    250284 ns/op	  166533 B/op	    1324 allocs/op
BenchmarkQueryRowsGORM-4                	    2000	    705297 ns/op	  399637 B/op	    6171 allocs/op
```

Don't require users to write collections.

---

db.go
tx.go
tx_test.go

Previously CopyFrom always executed in separate connection.

CopyFrom now can be used in transaction

---

.travis.yml

I'm explicitly adding 1.6 since it has been officially released. It would help me specifically know that 1.6 works as expected with this library.

Add 1.6 to travis for testing

---

db.go
messages.go

The call to `w.Close()` prevents `db.CopyTo` from writing multiple dumps to stdout like this:
db.CopyTo(os.Stdout, 'COPY mytable1 TO STDOUT')
db.CopyTo(os.Stdout, 'COPY mytable2 TO STDOUT')
I'm not sure if there is some reason for the call to Close(), the commit that introduced it does not mention it, so please approach this PR with caution.
Also, I'm new to Golang and this is my first Golang PR, so please bear with me :-).

Remove w.Close() from readCopyData()

---

orm/model_m2m.go
orm/model_many.go
orm/util.go

```
benchmark                            old ns/op     new ns/op     delta
BenchmarkModelHasOneGopg-4           285887        248198        -13.18%
BenchmarkModelHasManyGopg-4          3093718       3043229       -1.63%
BenchmarkModelHasMany2ManyGopg-4     3378445       3265400       -3.35%
benchmark                            old allocs     new allocs     delta
BenchmarkModelHasOneGopg-4           1173           1173           +0.00%
BenchmarkModelHasManyGopg-4          8595           6596           -23.26%
BenchmarkModelHasMany2ManyGopg-4     9618           8619           -10.39%
benchmark                            old bytes     new bytes     delta
BenchmarkModelHasOneGopg-4           77572         77500         -0.09%
BenchmarkModelHasManyGopg-4          407260        390425 …
```

orm: reduce number of allocation in many and m2m models.

---

db.go

Otherwise it will program runs out of pool connections and crashes with `pg: connection pool timeout`

Release acquired DB connections in db.CopyTo()

---

internal/pool/conn.go
messages.go

Before
```
BenchmarkQueryRowsGopgDiscard-4   	   20000	     75665 ns/op	     195 B/op	      16 allocs/op
```
After
```
BenchmarkQueryRowsGopgDiscard-4   	   20000	     74377 ns/op	      98 B/op	      15 allocs/op
```
Left allocations are coming from
- ParseInt which requires bytes -> string alloc
- reading columns

Add columns cache.

---

orm/insert_test.go
orm/table.go

Fixes https://github.com/go-pg/pg/issues/432

orm: ignore tableName of embedded struct.

---

options.go
options_test.go

It still works but tests don't compile any more.

Drop Go 1.6.

---

options.go
options_test.go

To make `ParseURL` working in Heroku I've changed default TLSConfig created when parsing database URL to have `InsecureSkipVerify=true` . This is a minimum for this to work in Heroku.
I've also set default database user name to 'postgres' because otherwise Postgres is throwing an error (not a case for Heroku but good to have).

InsecureSkipVerify and default database user name

---

options.go

Signed-off-by: Romain Beuque <romain.beuque@corp.ovh.com>

fix(documentation): PoolTimeout default value is incorrect

---

internal/parser/parser.go
orm/format_test.go

Fixes https://github.com/go-pg/pg/issues/745

parser: don't allow identifiers to start with underscore

---

orm/table.go

I encountered an issue with a table called `group` which triggered a syntax error from postgres (related to https://github.com/go-pg/pg/issues/496) as `GROUP` is a reserved keyword.
To fix that I checked the list of reserved keyword from [Postgres Documentation](https://www.postgresql.org/docs/current/static/sql-keywords-appendix.html) and added what would be possible table name to the check.
I also added a `strings.ToLower` call to the checked word as the check did not cover the case where a table is called `User` which can happen with database created by some previous ORM or a user.

orm: consolidate isPostgresKeyword

---

orm/field.go
orm/insert.go

Currently, it is not possible to create `NOT NULL` columns with `DEFAULT` values using `go-pg`,
because the `notnull` option causes zero values which otherwise represent `NULL` to be inserted in the database:
```go
type A struct {
Id   int64
Time time.Time `sql:",notnull,default:NOW()"`
}
func main() {
// [... database initialization ...]
a := &A{}
if err := db.Insert(a); err != nil {
panic(err)
}
log.Printf("%d %s\n", a.Id, a.Time)
// outputs: 1 0001-01-01 00:00:00 +0000 UTC
}
```
To let `go-pg` determine whether the zero value should be inserted or `DEFAULT` should be used, we can use **pointer types**:
```go
type B struct {
Id   int64
Time *time.Time `sql:",notnull,default:NOW()"`
}
func main() {
// [... database initialization ...]
b := &B{}
if err := db.Insert(b); err != nil { …
```

Omit zero value on notnull fields with default value

---

options.go
options_test.go

This commit updates the options.go file to accept postgresql as a
scheme.
As per the postgresql docs the scheme can either be postgres:// or
postgresql://
The general form for a connection URI is:
postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
The URI scheme designator can be either postgresql:// or postgres://. Each of the URI parts is optional.
It also updates a the test to include this additional option

Accept postgresql as scheme.

---

orm/model_table_struct.go

Soft delete fails when `deleted_at` column is mapped to a struct field of type `*time.Time`
`Panic: reflect.Set: value of type time.Time is not assignable to type *time.Time`

fix soft delete when deleted_at column is mapped to *time.Time

---

orm/table.go
orm/table_create.go
orm/table_create_test.go

This will allow a `tableSpace` string field to be added to a struct and will take the value of the name in the SQL tag and set the table space when creating a table.
https://www.postgresql.org/docs/current/manage-ag-tablespaces.html
I've made it so that it will also quote the tablespace names just to be safe (to be consistent with quoting table names).
I would love feedback!

Added support for tablespaces in models.

---

orm/count_estimate.go

This allows context to be passed into the after hooks.

Pass context down CountEstimate queries.

---

base.go
race_test.go

When passing a timeout context into the db queries, there currently
exists a race condition where a select between query finish and context
done can choose the context, and go on to send a cancel request on a
conn that has already been freed. So a concurrent request may pick up
the same conn but is cancelled by this orphaned request.
There is a similar fix in https://github.com/lib/pq/pull/578 where we
use the same channel to pass flow between fn finish and cancel
goroutines. close() is async so a select cannot guarantee executing one
case at a time.
Added a test in race_test to prove the problem and the fix.

db: fix cancel request race condition on context timeout/cancellation

---

orm/insert.go
orm/insert_test.go

Fixes an error introduced in #1185 where brackets where missing in a switch-case in `orm/insert.go`.

Fix: Add missing brackets and add test for that case

---

options.go
options_test.go

This commit adds support for connect_timeout option in the connection
string parsed by ParseURL function.
Support for this option provides more compatibility with libpq.
Ref: https://www.postgresql.org/docs/9.6/libpq-connect.html

Add support for connect_timeout option

---

orm/table.go
orm/table_create.go
orm/table_create_test.go

This will allow a model's table to be created with options for partitions.
Allowing users to then create the individual partition tables manually
but still letting go-pg/pg manage the initial table creation.
The main reason for this is; we are using an account_id column for all of our tables. But we want to partition our tables using PostgreSQL's partition feature by account_id and hash. We also want to add some partitioning even further on some of those tables where we keep archived or deleted records in their own partition on a tablespace that resides on a slower hard drive. While keeping active records on a different partition on a faster tablespace.
This will make it so the initial creation of our tables is much easier, and we can manage creating the individual partitions manually by …

Added support for creating model tables with partition options.

---

orm/update.go
orm/update_test.go

In a batch update it already correctly asserts that a zero value field
should be represented as such. But because it sends all data in the
update during a batch update it can still overwrite the existing value.
This solves that problem by adding a COALESCE around the value set
portion of the update statement so that if the value provided from the
ORM is null then it will not overwrite the existing database value.
This only affects updates done with slices. Single record updates 
behave as they should currently.

Added support for omitting zero values from batch updates.

---

orm/table.go
orm/table_create.go

Updates https://github.com/go-pg/pg/pull/1329

Normalize bigserial to bigint. Use pkSQLType only when creating a table.

---

orm/update.go
orm/update_test.go

When performing a bulk update previously it would try to cast the fields
that were "bigserial" or "serial" to those types in the from clause. But
because they are not actual types in PostgreSQL and are just aliases, it
would cause an error when executing the query. This resolves that by
making sure that serial columns are cast to their base type instead.
This fixes the error:  `[42704] ERROR: type "bigserial" does not exist`

Added handling of serial column types in updates.

---

orm/table.go
orm/table_create.go
orm/update.go
orm/update_test.go

This PR backports #1329 and #1331 to the v8 branch, to address #1351. #1351 is already fixed in master, but this will help people (including yours truly) who are stuck on v8 until v9 stabilizes.
Thanks for taking a look!

Backport #1329 and #1331 to v8 branch

---

orm/insert_test.go
orm/table.go

This was because we were trying to read the Uint value from the
reflection, but we had the pointer, not the actual reflected value. This
fixes the problem by checking to see if we were given a pointer and if
it is it will get the value from the address.

Fixed issue where pointer uint64 values would panic during inserts.

---

orm/join.go
orm/select_test.go

This fixes a problem where you could have a chain of one to one relationships
that could cause a strange query error if the top most model is a soft delete
model. 
To reproduce this problem on the current version of go-pg create the following
models.
```golang
type SoftDeleteParent struct {
Id          uint64 `sql:"id,pk"`
Name        string
DateDeleted *time.Time `pg:",soft_delete"`
Children *SoftDeleteChild
}
type SoftDeleteChild struct {
Id                 uint64            `sql:"id,pk"`
SoftDeleteParentId uint64            `sql:"soft_delete_parent_id,on_delete:CASCADE"`
SoftDeleteParent   *SoftDeleteParent `sql:"-"`
Name               string
SubChildren        *SoftDeleteSubChild
}
type SoftDeleteSubChild struct {
Id                uint64           `sql:"id,pk"`
SoftDeleteChildId …
```

Fixed issue with chained one to one joins with a parent soft delete.

---

db_test.go

Previously, the test that checks that an error is returned when
PREPARE'ing a bogus SQL statement would check for the precise error
message. Now, the test will check that the correct error code is
returned as well as a reasonable error message (i.e. the matching
is less strict yet should be sufficient). The reason for the change
is that other databases that "speak" Postgres (for example CockroachDB)
might return an error that slightly deviates from PG but is still
reasonable.

Loosen up error matching in test

---

db_test.go
options.go

This commit adds the support of some environment variables (namely,
PGHOST, PGPORT, PGUSER, PGDATABASE, and PGSSLMODE) that override
certain options when running tests. The inspiration is taken from
lib/pq tests (https://www.postgresql.org/docs/9.3/libpq-envars.html).
For every option, the corresponding environment variable is first
checked. If it is present, then the value is used; if it is not present
or empty, then we fall back to using the default values.

Introduce environment variables to customize running tests

---

orm/join.go
orm/select_test.go

When a non soft delete table was the base table the query builder would
panic when it tried to add the soft delete criteria to the join ON
criteria. This was because we were properly evaluating that a soft
delete filter should be added on the join. But we were adding it for the
wrong table and trying to add it for a table where the soft delete
column was nil causing a panic.
This resolves the problem by making the ON filter for a soft delete join
for the actual join/soft deletable table rather than the base table.
To test this you can run the following test on the current master branch 9ab62c0f9c17851e2926c019d0262f198576930e and see how it fails:
```golang
var _ = Describe("SoftDeleteModel", func() {
It("will join a non-SoftDelete with a SoftDelete", func() {
type NonSoftDeleteModel …
```

Fixed bug when joining a non soft delete table with a soft delete table.

---

orm/hook.go

When using AfterSelectHook and then the model has `has many` relation, error occured
```
reflect: call of reflect.Value.Len on zero Value
/usr/local/go/src/reflect/value.go:1086 (0x1087bed)
Value.Len: panic(&ValueError{"reflect.Value.Len", v.kind()})
/Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/hook.go:75 (0x16cabea)
callHookSlice2: for i := 0; i < slice.Len(); i++ {
/Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/hook.go:128 (0x16d7182)
callAfterSelectHookSlice: return callHookSlice2(c, slice, ptr, callAfterSelectHook)
/Users/firmanalamsyah/Documents/go/src/github.com/go-pg/pg/orm/model_table_slice.go:113 (0x16d712f)
(*sliceTableModel).AfterSelect: return callAfterSelectHookSlice(c, m.slice, m.sliceOfPtr) …
```

bug fix when AfterSelect hook called in has many relation

---

base.go
orm/query.go

Fix #1464 
Just the same as #1374 , but this time for `baseDB`.

Use db.db.Context() instead of creating new context

---

orm/model_table_slice.go

This fixes two pointer related issues related to batch (slice) soft deleting.
1. Soft deleting a slice of pointer models with non-pointer soft delete fields.
2. Soft deleting a slice of non-pointer models with pointer soft delete fields.
Based on what I'm seeing in `structTableModel`, it would seem that using the recently introduced `Table.SetSoftDeleteField` function is the right way to go.

Use SetSoftDeleteField in sliceTableModel
